/*
* SLChart.js
*
* Zach Toogood February 2015
* zrtoogood@gmail.com
* zachtoogood.com
*
* The purpose of this file is to take the URL of a StrongLifts backup file (a .csv generated by the StrongLifts App) and
* generate a chart using Chart.js or ChartNew.js (by francois.vancoppenolle@favomo.be, http:\\www.favomo.be\graphjs).
*
*
*
*/


	//Get Data
        Papa.parse("http://zachtoogood.com/files/FitChart/data/spreadsheet-stronglifts.csv", {
		download: true,
            dynamictyping: true,
		complete: function(results) {
			//console.log(results);
            drawChart(results);
		}
	});

    function drawChart(_data){
        //Set Data
        var labels = [];
        var ydata = [];
        var xdata = [];

        for (i = 1; i < _data.data.length - 1; i++) { //i = 1 ignore header
            var d = _data.data[i][0]; //Date
            var x = parseFloat(_data.data[i][3]); //BW
            var y = parseFloat(_data.data[i][5]); // Squat

            if (x < 10){
                x = undefined;
            }

            labels.push(d);
            ydata.push(y);
            xdata.push(x);

            console.log(d + " " + x + " " + y + " ");
            }

        //Define Chart
        var LineChart = {
            labels: labels,
            datasets: [ {
                label: "Bodyweight (kg)",
                fillColor: "rgba(252,10,10,0.6)",
                strokeColor: "rgba(252,10,10,0.5)",
                pointColor: "rgba(252,10,10,0.5)",
                pointStrokeColor: "rgba(252,10,10,0.5)",
                data: xdata,
                skipNullValues: true
            },{
                label: "Squat (kg)",
                fillColor: "rgba(10,10,249,0.6)",
                strokeColor: "rgba(10,10,249,0.5)",
                pointColor: "rgba(10,10,249,0.5)",
                pointStrokeColor: "rgba(10,10,249,0.5)",
                data: ydata,
                skipNullValues: true
            }]
        }

        //Draw Chart
        var myLineChart = new Chart(document.getElementById("canvas").getContext("2d")).Line(LineChart,
                {
                    scaleFontSize : 13,
                    scaleFontColor : "#000000",
                    //Boolean - If we want to override with a hard coded scale
                    scaleOverride: true,
                    scaleSteps: 12,
                    scaleStepWidth: Math.ceil(10),
                    scaleStartValue: 0
                });

        legend(document.getElementById("placeholder"), LineChart);
    }